# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/configuration-reference/#jobs
jobs:
  say-hello:
    deploy-job:
      steps:
        - add_ssh_keys:
            fingerprints:
    # Specify the execution environment. You can specify an image from Docker Hub or use one of our convenience images from CircleCI's Developer Hub.
    # See: https://circleci.com/docs/configuration-reference/#executor-job
    docker:
      - image: cimg/base:stable
    # Add steps to the job
    # See: https://circleci.com/docs/configuration-reference/#steps
    steps:
      - add_ssh_keys:
          fingerprints:
          - 00:ea:d5:04:09:b5:de:19:71:3a:80:9c:0a:58:ed:fb
      - checkout
      - run:
          name: "Say hello"
          command: |
            export HASH=$(git rev-parse --short HEAD)
            git tag new-1 $HASH
            git push origin new-1
          

# Orchestrate jobs using workflows
# See: https://circleci.com/docs/configuration-reference/#workflows
workflows:
  say-hello-workflow:
    jobs:
      - say-hello
      
